// Code generated by core_generate; DO NOT EDIT.

package address

import (
	"sync"

	"github.com/griffnb/core/lib/log"
	"github.com/griffnb/core/lib/model"
	"github.com/griffnb/core/lib/model/coremodel"
	"github.com/griffnb/core/lib/model/fields"
	"github.com/griffnb/core/lib/tools"
)

var registerOnce sync.Once
var Columns *Address

const (
	PACKAGE string = "address"
	MODEL   string = "Address"
)

func init() {
	RegisterFields()
	Columns = New()
}

func RegisterFields() {
	registerOnce.Do(func() {
		fields.RegisterFieldTypes(&Structure{})
	})
}

func New() *Address {
	return NewType[*Address]()
}

func NewType[T initializable]() T {
	obj := tools.NewObj[T]()
	obj.InitializeWithChangeLogs(&model.InitializeOptions{
		Table:       TABLE,
		Model:       MODEL,
		ChangeLogs:  CHANGE_LOGS,
		Package:     PACKAGE,
		IsVersioned: IS_VERSIONED,
	})
	err := fields.InitializeFields(obj)
	if err != nil {
		log.Error(err)
	}
	return obj
}

type initializable interface {
	coremodel.Model
	InitializeWithChangeLogs(*model.InitializeOptions)
	Load(result map[string]any)
}

func load[T initializable](result map[string]any) T {
	obj := NewType[T]()
	obj.Load(result)
	return obj
}

func As[T initializable, V initializable](source T) V {
	target := NewType[V]()
	target.SetData(source.GetDataCopy())
	return target
}
